#!/bin/sh

mod="Mod4"

riverctl map normal $mod+Shift Return spawn alacritty

# Mod+P to run applications
riverctl map normal $mod P spawn bemenu-run

riverctl map normal $mod       Space spawn "makoctl dismiss"
riverctl map normal $mod+Shift Space spawn "makoctl dismiss --all"

riverctl map normal $mod S spawn 'grim -g "$(slurp)" - | wl-copy'
riverctl map normal Mod4+Shift S spawn 'grim -g "$(slurp)" "$(echo "$HOME/screenshots/$(date "+%Y%m%d_%H%M%S").png" | tee >(wl-copy -n))"'

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+E to exit river
riverctl map normal $mod+Shift E exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma  focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma  send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

map_tags_set() {
	key="$1"
	tags="$2"

	riverctl map normal Mod4       "$key" set-focused-tags "$tags"
	riverctl map normal Mod4+Shift "$key" set-view-tags    "$tags"
}

map_tags_toggle() {
	key="$1"
	tags="$2"

	riverctl map normal Mod4+Control       "$key" toggle-focused-tags "$tags"
	riverctl map normal Mod4+Shift+Control "$key" toggle-view-tags    "$tags"
}

map_tags() {
	key="$1"
	tags="$2"

	map_tags_set    "$key" "$tags"
	map_tags_toggle "$key" "$tags"
}

tags() {
	echo $((1 << $1))
}

map_tags u $(tags 0)
map_tags i $(tags 1)
map_tags o $(tags 2)
map_tags n $(tags 3)
map_tags m $(tags 4)
# Affects all tags
map_tags_set y $(($(tags 32) - 1))

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Set background and border color
riverctl background-color       0x002b36
riverctl border-color-focused   0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set repeat rate
riverctl set-repeat 50 300

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

exec mako &
exec rivertile -view-padding 3
