source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "raiguard/one.kak" theme config %{
	colorscheme one-dark
}

plug "kak-lsp/kak-lsp" do %{
	cargo install --locked --force --path .
} config ${
	hook global WinSetOption filetype=go %{
		lsp-enable-window
		lsp-auto-hover-enable

		hook window BufWritePre .* lsp-formatting-sync

		map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
	}
}

hook global WinCreate ^[^*]+$ %{
    add-highlighter window number-lines
}

hook global RegisterModified 'y' %{ nop %sh{
	printf %s "$kak_main_reg_dquote" | xclip -in -selection clipboard >&- 2>&-
}}
