source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "raiguard/one.kak" theme config %{
	colorscheme one-dark
}

plug "https://git.tchncs.de/notramo/elvish.kak"

plug "kak-lsp/kak-lsp" do %{
	cargo install --locked --force --path .
} config %{
	hook global WinSetOption filetype=go %{
		lsp-enable-window
		lsp-auto-hover-enable

		hook window BufWritePre .* lsp-formatting-sync

		map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
	}
}

hook global WinCreate ^[^*]+$ %{
    add-highlighter window/ number-lines -hlcursor
}

hook global RegisterModified 'y' %{ nop %sh{
	printf %s "$kak_main_reg_dquote" | xclip -in -selection clipboard >&- 2>&-
}}

define-command -params 1.. run %{
	evaluate-commands %sh{
		output="$(mktemp -d -t kak-run-XXXXXXXX)/fifo"
		mkfifo "${output}"

		case "$1" in
			*.go)
				{ go run "${1}" "${@:2}" > "${output}"; } > /dev/null 2>&1 < /dev/null &
			;;
			*)
				echo "No runner configured" >&2
				exit
		esac

		pid="$!"

		# Ensure that there are never duplicate buffer names
		tmp="${output//*-/}"
		tmp="${tmp//\/*/}"

		echo "edit! -fifo ${output} -scroll -readonly *run-${tmp}*"
		echo "hook buffer BufClose .* %{ nop %sh{ kill ${pid} && rm -r $(dirname ${output})} }"
	}
}
