theme = "onelight"

[keys.normal.space.l]
l = "buffer_picker"
j = "goto_next_buffer"
k = "goto_previous_buffer"
d = ":buffer-close"
D = ":buffer-close!"
o = ":buffer-close-others"
O = ":buffer-close-others!"
a = ":buffer-close-all"
A = ":buffer-close-all!"
